Add Google and Kotlinlang support
facebookincubator/ktfmt pull request #183
Opened 2021-02-26 22:04 UTC by JavierSegoviaCordoba

2021-02-27 19:19 UTC, cgrushko requested changes
Thank you very much for this contribution!
I left some comments, I hope they make sense.
Thanks again!

2021-02-27 19:19 UTC, cgrushko commented on ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/FormatterUtil.java
> +    FormattingOptions formattingOptions;
`final FormattingOptions formattingOptions;`

will make the compiler verify it's set exactly once, which makes it safer.

But - see my comment in KtfmtSettings.java before working on this file.

2021-02-27 19:19 UTC, cgrushko commented on ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/KtfmtConfigurable.java
> +import javax.swing.*;
replace .* with individual imports

2021-02-27 19:19 UTC, cgrushko commented on ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/UiFormatterStyle.java
> -  UiFormatterStyle(String description, boolean isDropboxStyle) {
instead of `boolean isDropboxStyle`, use `FormattingOptions formattingOptions`.
Then, initialize like that -
```
DEFAULT("Default", new FormattingOptions()),
DROPBOX("Dropbox", com.facebook.ktfmt.DROPBOX_FORMAT),
GOOGLE("Google (internal)", GOOGLE_FORMAT),
KOTLINLANG("kotlinlang.org", KOTLINLANG_FORMAT),

then, you don't need the switch in FormatterUtil.java, you can directly use the field.

```

2021-02-27 19:19 UTC, cgrushko commented on ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/UiFormatterStyle.java
> +  static UiFormatterStyle convert(UiFormatterStyle uiFormatterStyle) {
we don't need this method anymore - delete it entirely

2021-02-27 19:23 UTC, JavierSegoviaCordoba commented on ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/FormatterUtil.java
> +    FormattingOptions formattingOptions;
That is very funny, I was trying to use `switch` like it was an enum in Kotlin until I remembered I can't.

2021-02-28 00:10 UTC, JavierSegoviaCordoba commented on ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/FormatterUtil.java
> +import static com.facebook.ktfmt.FormatterKt.*;
I am checking that the order of some imports in multiple files has changed. I was using the Google plugin plus reformat code + optimize imports

2021-02-28 07:21 UTC, cgrushko commented on ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/FormatterUtil.java
> +import static com.facebook.ktfmt.FormatterKt.*;
Unfortunately the GJF plugin doesn't sort imports (unclear why). In general, to preserve blame and history it's best not to change anything unrelated to your change.
I'll sort them after importing to our internal repo, our linters will complain anyway.

2021-02-28 07:54 UTC, JavierSegoviaCordoba commented on ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/FormatterUtil.java
> +import static com.facebook.ktfmt.FormatterKt.*;
Spotless does? It has Google format for java.

2021-03-02 06:34 UTC, closed without merging