Support `expect enum class` without a body.
facebookincubator/ktfmt pull request #263
Opened 2021-12-14 16:04 UTC by mpetrov

Currently the parser breaks when encountering these in mutliplatform
projects.

2021-12-14 20:12 UTC, hick209 approved these changes
Thanks for helping improve ktfmt

2021-12-15 16:39 UTC, mpetrov commented
I don't have permissions to run the `Build and Test`  check or merge, so let me know if there's any more action needed on my end.

2021-12-18 02:58 UTC, mpetrov commented
Updated due to conflict with `main`. Sorry but will need approval again to rerun the workflows since I'm a first time contributor, and I'd also need someone authorized to merge to actually merge the request afterwards.

2021-12-19 20:18 UTC, cgrushko requested changes

2021-12-19 20:18 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +          visitEnumBody(classOrObject as KtClass)
does it make sense checking if `body` is null inside `visitEnumBody`? that method is only called from here right now, but I think it makes it easier to read the code overall.

2021-12-19 20:18 UTC, cgrushko commented on core/src/test/java/com/facebook/ktfmt/format/FormatterTest.kt
> +  fun `expect enum class`() =
can you move this alongside the other `enum` tests? around line 3390

2021-12-19 20:21 UTC, cgrushko commented
@mpetrov , thank you very much for this contribution! I left a couple of comments.

Re merging - since ktfmt's source of truth is Meta's internal repo, we won't merge this PR directly. Instead, we'll land the diff that was created above (mentioned in https://github.com/facebookincubator/ktfmt/pull/263#issuecomment-993979043) and then it'll be exported to the repo on GitHub. You'll be credited as the author.

2021-12-19 23:32 UTC, mpetrov commented on core/src/test/java/com/facebook/ktfmt/format/FormatterTest.kt
> +  fun `expect enum class`() =
Good call, done.

2021-12-19 23:32 UTC, mpetrov commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +          visitEnumBody(classOrObject as KtClass)
SGTM, done.

2021-12-19 23:42 UTC, mpetrov commented
I assumed github was the source of truth, thanks for the context @cgrushko! Made the suggested changes.

2021-12-20 21:13 UTC, cgrushko commented
Started landing in the source-of-truth repo, this PR should auto-close when it lands

2021-12-20 21:37 UTC, closed without merging