Fix formatting of block-like lambdas (+ scope functions) on long lines.
facebookincubator/ktfmt pull request #280
Opened 2022-02-10 19:19 UTC by nreid260

If everything up to and including the `->` can fit on the current line, then indent only the lambda body. If we must break before the `->`, treat the lambda and scoping function as an expression, and indent the entire thing into a rectangle.

2022-02-13 07:30 UTC, cgrushko commented
Importing for easier review

2022-02-13 11:13 UTC, cgrushko requested changes
Please separate this from https://github.com/facebookincubator/ktfmt/pull/282 and run ktfmt on the code :)

2022-02-14 06:53 UTC, cgrushko requested changes

2022-02-14 06:53 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    val bracePlusBlockIndent = ifBrokeBeforeBrace(blockPlusExpressionBreakIndent, blockIndent)
this shows up both here and in https://github.com/facebookincubator/ktfmt/pull/282....

2022-02-14 08:21 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    val bracePlusBlockIndent = ifBrokeBeforeBrace(blockPlusExpressionBreakIndent, blockIndent)
#282 is stacked on top of this PR

2022-02-15 12:07 UTC, cgrushko commented
Applied the changes to our repo, things look awesome, this is a great fix :) :) :)

2022-02-15 12:13 UTC, closed without merging