Lambda indent assignment
facebookincubator/ktfmt pull request #282
Opened 2022-02-11 19:01 UTC by nreid260

2022-02-13 11:01 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    val lambda =
please replace this with if-else with each branch calling visitLambdaExpression(), unless I'm missing why this can't be done?

2022-02-13 11:02 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> -      builder.guessToken(";")
merge conflict?

2022-02-13 16:24 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    val lambda =
I don't understand the requested change.

2022-02-13 16:28 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    val lambda =
Does this work? if yes, I prefer this over mixing statements and expressions in the `lambda` variable.

```
 when (expr) {
    is KtLambdaExpression -> { 
       visitLambdaExpression(expr, breakToExpr)
    }
    is KtCallExpression -> {
      visit(expr.calleeExpression)
      builder.space()
      visitLambdaExpression(expr.lambdaArguments[0].getLambdaExpression()!!, breakToExpr)      
    }
    else -> throw AssertionError(expr)
  }
```

2022-02-13 18:00 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +  private fun isLambdaOrScopingFunction(initializer: PsiElement?): Boolean {
Done

2022-02-13 18:00 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> -      builder.guessToken(";")
Done.

2022-02-13 18:00 UTC, nreid260 commented on core/src/test/java/com/facebook/ktfmt/format/FormatterTest.kt
> -  fun `don't crash on top level statements with semicolons`() {
Done.

2022-02-14 06:53 UTC, cgrushko requested changes

2022-02-14 06:53 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +     * Enable correct formatting of the `fun foo() = scope {` syntax.
this shows up in both PRs...

2022-02-14 08:20 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +     * Enable correct formatting of the `fun foo() = scope {` syntax.
This is supposed to be a stacked on top of #280 Is there some special way of representing that? In my local repo it's a branch off of #280 branch

2022-02-15 11:22 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +     * Enable correct formatting of the `fun foo() = scope {` syntax.
No idea, we're not using git and/or github internally 🤷‍♂️

2022-02-15 16:54 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +     * Enable correct formatting of the `fun foo() = scope {` syntax.
Neither are we, haha. I'm jumping through all kinds of hoops to sync my changes in and out of our actual repo.

2022-02-15 20:17 UTC, cgrushko commented
> I've rebased this. It's now very simple.

thanks!! I managed to do so internally but this will let me re-import more easily.

we're now debating internally whether it's a good idea.
The original reason for this block-like behavior was to write functions whose bodies are scoped, and them to still look like functions. But assigning lambdas to variables feels like there's no reason they look like functions...

2022-02-15 20:34 UTC, nreid260 commented
Our motivation here is DSLs (and at Google that means protobufs!)

```
val foo = fooProto {
  bar += barProto {
    zip = 1
    zap = 0
    qux = quxProto {
      zop = 3
    }
  }
}
```

2022-02-15 20:36 UTC, cgrushko commented
_Interesting_!
Ok, I'll update on our discussions. I applied it to our repo and got some stuff I didn't like on first glance, but I'm unfamiliar with the context it's used internally.

2022-02-16 17:08 UTC, closed without merging