Fix a bunch of build warnings
facebookincubator/ktfmt pull request #283
Opened 2022-02-13 18:55 UTC by nreid260

2022-02-14 06:51 UTC, cgrushko requested changes
There are some build errors reported by CI

2022-02-15 11:21 UTC, cgrushko commented
Java 13 still has failures - can you see the logs? (not sure about the permissions here)

2022-02-15 23:35 UTC, nreid260 commented
I can see them, but I don't understand what would be different. Do you have a minute to take a look? The goal here is just to stop kotlinc from spamming so much.

2022-02-25 15:15 UTC, cgrushko commented
No idea; does it build successfully locally for you on Java 13?

2022-02-25 17:32 UTC, nreid260 commented
Looks like it was some kind of incompatibility with Guava 31

2022-04-13 18:03 UTC, nreid260 commented
Poke

2022-04-13 19:19 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInput.kt
> +          else -> length
should this be `else -> 1`, at least to preserve the current behavior?

2022-04-13 19:19 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInput.kt
> +    return ImmutableMap.copyOf(builder)
what's the build warning here?

2022-04-13 19:19 UTC, cgrushko commented on core/pom.xml
> +            <artifactId>kotlin-stdlib-jdk7</artifactId>
what's the build warning here?

2022-04-13 19:25 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInput.kt
> +          else -> length
This should preserve the current behaviour. `length = 1` isn't a case, it's the behaviour when `length == 0`.

2022-04-13 19:33 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInput.kt
> +    return ImmutableMap.copyOf(builder)
`ImmutableMap.Builder.build()` throws if there are are duplicate keys. This caused enough confusion that a preferred, explicit method `buildOrThrow` was added in Guava 31.0. Google builds from the newest version of Guava. https://guava.dev/releases/31.0.1-jre/api/docs/com/google/common/collect/ImmutableMap.Builder.html#build()

2022-04-13 19:34 UTC, nreid260 commented on core/pom.xml
> +            <artifactId>kotlin-stdlib-jdk7</artifactId>
I believe this is needed for the changes to core/src/test/java/com/facebook/ktfmt/cli/MainTest.kt

2022-04-13 19:45 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInput.kt
> +          else -> length
/facepalm

2022-04-13 19:48 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInput.kt
> +    return ImmutableMap.copyOf(builder)
Got it. I think it's fine this time, but we'll keep running into these problems, since Meta / OSS isn't aware of Guava 31.
Don't know if policy allows that, but you may want to consider adding Guava 29 to third-party (and limiting its `visibility` to ktfmt).

2022-04-13 20:33 UTC, strulovich requested changes

2022-04-13 20:33 UTC, strulovich commented on core/src/main/java/com/facebook/ktfmt/format/TypeNameClassifier.kt
> +          hasLowercase = hasLowercase or Character.isLowerCase(char)
If you're changing this how about using the Kotlin extension methods?

2022-04-13 20:33 UTC, strulovich commented on core/src/test/java/com/facebook/ktfmt/cli/MainTest.kt
> +  private val root = createTempDirectory().toFile()
What's the issue here?

2022-04-13 20:33 UTC, strulovich commented on core/src/test/java/com/facebook/ktfmt/format/FormatterTest.kt
> +  fun `handle qmark for nullalble types`() =
"question mark" please

Let's avoid abbreviations for easier readability

2022-04-13 20:35 UTC, cgrushko commented on core/src/test/java/com/facebook/ktfmt/cli/MainTest.kt
> +  private val root = createTempDirectory().toFile()
`createTempDir` is marked deprecated

2022-04-14 20:02 UTC, closed without merging