Introduce FluentChain class for formatting qualified expressions
facebookincubator/ktfmt pull request #294
Opened 2022-02-24 17:59 UTC by nreid260

This fixes several issues around formatting chains with trailing lambdas, array acccess, and the !! operator. It should also be easier to understand and extend in the future.

Right now this path is only use when --google_style is set.

2022-02-24 20:30 UTC, cgrushko commented
1. importing for easier review
2. Can we move the branching between google and non-google styles into the FluentChain class? first, this looks like something that can benefit non-Google styles. second, I don't want big branches in the code.

2022-02-24 20:36 UTC, nreid260 commented
> 2. Can we move the branching between google and non-google styles into the FluentChain class? first, this looks like something that can benefit non-Google styles. second, I don't want big branches in the code.

I'm not sure what that would look like. Right now, there's only one branch related to `FluentChain`, which is inside `interceptFluentChainForGoogleStyle`.

I'd be happy to have other styles use `FluentChain`, but I was afraid to touch the existing code related to qualified expressions. There are a lot of heuristics/special cases that I didn't want to interfere with.

Could be try to get this merged just for google-style? After that, owners of other styles can experiment with how to leverage `FluentChain` to fit their needs.

2022-02-25 16:02 UTC, strulovich requested changes
This is small nit, I think @cgrushko's point is more important.

I'm okay with support changes for Google style, but this feels like a big fork in the code, and it's not really clear what it gets that is really important.

We are supportive of improving call chains, and prefer to build something that works for both Google & others at the same time, else we may find more forks down the line and this will become unwieldy (as you said, all those edge cases are challenging, so we want to avoid extra edge cases)

@davidtorosyan is trying to get some similar things working on our side, but didn't quite nail it all yet.

Is there something that this diff achieves that more of a deal breaker than other things which we can prioritize?

2022-02-26 00:39 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +     */
I've added one of the new google_style test cases to `FormatterTest`. It illustrates some of the issues I'm trying to resolve. Most apparently, the current approach to qualified expressions doesn't understand `[]` or`!!`, among other left-associative operator-like constructs.

2022-02-26 00:54 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +     */
I guess another issue is that the other styles seem to want to bunch multiple links of a fluent chain onto the same line, with lots of heuristics about exactly how to do that. There are tests many tests about stuff like:

```
red.orange.yellow
  .green blue.indigo
  .violet (
    are = colors,
  )
```

We don't think this bunching is good thing, and would rather not have it. Supporting it also seems to substantially increase complexity. That's why I'm effectively trying to rewrite support for fluent chains.

As I said, I'd be glad for all styles to use our approach going forward, but I don't know how committed others are to how things currently work.

2022-02-26 01:19 UTC, davidtorosyan commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +     */
Hi @nreid260, I added a bunch of those tests specifically to highlight the wonky behavior. 

More specifically, I was attempting to lay out all the ways we handle this formatting today and then make a couple of changes which would simplify things dramatically.

Things didn't go exactly as planned so I've put it on the backburner, but suffice it to say we're a) very interested in solving the problem for all styles, b) not married to the current approach.

The trick right now is figuring out what we want it to look like. I'm typing this from my phone so sorry if missed any updates, but the initial description didn't make the goal very clear. Could you tell me what the general principle is of the new formatting you had in mind?

2022-02-26 08:37 UTC, davidtorosyan commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +     */
Thanks for the clarification!

A couple things I'm not sure about:
1. What you're calling a "call chain" or "fluent chain", I'd call a "qualified expression" (my changes have been mostly in that visitor). Are these not the same thing?
2. What do you mean when you say that call chains might not align with the AST? How would we then be able to detect and manipulate them?
3. What do you mean by "block like" in reference to call expressions?

2022-03-04 19:14 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +     */
It also occurs to me that `::` should be considered one of the dereference operators. Example:

```
foo
  .bar
  ::baz
```

2022-03-04 19:32 UTC, nreid260 commented
Since this seems to be a larger discussion, I've extracted out my key points into https://github.com/facebookincubator/ktfmt/issues/296

2022-07-23 23:23 UTC, closed without merging