For --google_style, break between ( and long condition expressions
facebookincubator/ktfmt pull request #325
Opened 2022-06-02 16:55 UTC by nreid260

Fixes https://github.com/facebookincubator/ktfmt/issues/319

2022-06-06 07:33 UTC, cgrushko commented
Importing for easier review

2022-06-07 02:08 UTC, strulovich requested changes

2022-06-07 02:08 UTC, strulovich commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +
We organize methods by chronological order if possible, so caller before callee. Could you move these below all callers?

2022-06-07 02:08 UTC, strulovich commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +  private fun emitKeywordWithCondition(keyword: String, condition: KtExpression?) {
Please add a KDoc. 

We usually state example of the content this parses, so something alike:

```
/** Emits a key word followed by a condition, e.g. `if (b)` or `while (c <d )` */
```

2022-06-07 02:38 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +  private fun emitKeywordWithCondition(keyword: String, condition: KtExpression?) {
Done

2022-06-07 02:38 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +
Done

2022-06-07 13:12 UTC, strulovich approved these changes
Thanks!

2022-06-07 21:38 UTC, closed without merging