Add --stdin-name to specify a file name to use when printing message about stdin input
facebookincubator/ktfmt pull request #336
Opened 2022-07-06 23:51 UTC by nreid260

Closes https://github.com/facebookincubator/ktfmt/issues/335

2022-07-21 06:44 UTC, cgrushko requested changes

2022-07-21 06:44 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +    /** Name to report when formating code from stdin */
"File name to report when ..."

2022-07-21 06:44 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      var fileNames = mutableListOf<String>()
why the change?

2022-07-21 06:44 UTC, cgrushko commented on core/src/test/java/com/facebook/ktfmt/cli/MainTest.kt
> +    assertThat(err.toString("UTF-8")).contains("--stdin-name")
use the entire error string? for documentation purposes

2022-07-21 06:44 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +          arg.startsWith("--stdin-name=") -> stdinName = arg.split('=', limit = 2)[1]
add validation here (and tests) - 
if there's no `=` after `--stdin-name`, tell the user how to use it (in particular, this will reduce confusion around `--stdin-name foo.kt`)

does this crash if the user inputs `--stdin-name=` (with nothing after the `=`)?

2022-07-21 07:55 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +    /** Name to report when formating code from stdin */
Done.

2022-07-21 07:55 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      var fileNames = mutableListOf<String>()
Reverted.

2022-07-21 07:55 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +          arg.startsWith("--stdin-name=") -> stdinName = arg.split('=', limit = 2)[1]
Done.

2022-07-21 08:10 UTC, nreid260 commented on core/src/test/java/com/facebook/ktfmt/cli/MainTest.kt
> +    assertThat(err.toString("UTF-8")).contains("--stdin-name")
Done.

2022-07-22 17:54 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/cli/Main.kt
> +    val fileName = file?.toString() ?: parsedArgs.stdinName ?: "<stdin>"
if you're in the mood, we can make stdinName = "<stdin>" by default, and make it non-nullable, and then always use it as is

2022-07-22 17:54 UTC, cgrushko commented
(I'm waiting for internal review now)

2022-07-22 18:04 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/cli/Main.kt
> +    val fileName = file?.toString() ?: parsedArgs.stdinName ?: "<stdin>"
It might be better if the default value were `""`, since then users could explicitly pass the default value on the CLI.

However, it would be bad if error messaged printed `""` as the file name when it isn't specified. Maybe
```
val fileName = file?.toString() ?: (if (parsedArgs.stdinName.isEmpty()) { "<stdin>" } else { parsedArgs.stdinName })
```

2022-07-24 06:46 UTC, cgrushko commented on core/src/main/java/com/facebook/ktfmt/cli/Main.kt
> +    val fileName = file?.toString() ?: parsedArgs.stdinName ?: "<stdin>"
I'm not sure I understand the use-case, but let's not spend more time on this

2022-07-24 07:38 UTC, closed without merging

2022-07-24 14:58 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/cli/Main.kt
> +    val fileName = file?.toString() ?: parsedArgs.stdinName ?: "<stdin>"
I don't expect to have to pass `""` myself, but I know from other CLIs that its helpful to be able to pass defaults explicitly, particularly when writing shell scripts.